# Generated by Django 4.2.2 on 2023-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('loc', models.CharField(max_length=200, verbose_name='Item Location')),
                ('dist', models.CharField(blank=True, default='', max_length=200, verbose_name='Distance')),
                ('price', models.CharField(max_length=20, verbose_name='Price (GBP)')),
                ('img', models.CharField(max_length=500, verbose_name='Image URL')),
            ],
        ),
    ]
